Enum "Role" {
  "ADMIN"
  "MANAGER"
  "MEMBER"
  "FORMER_MEMBER"
}

Enum "TaskPriority" {
  "LOW"
  "MEDIUM"
  "HIGH"
}

Enum "TaskStatus" {
  "TODO"
  "IN_PROGRESS"
  "IN_REVIEW"
  "DONE"
}

Enum "TaskType" {
  "TODO"
  "MONTHLY_SEGMENTS"
  "PUBLICATION"
  "EVENT"
  "MEETING"
  "TRAINING"
  "WORKSHOP"
}

Enum "UserStatus" {
  "ACTIVE"
  "INACTIVE"
  "BANNED"
}

Table "_prisma_migrations" {
  "id" varchar(36) [pk, not null]
  "checksum" varchar(64) [not null]
  "finished_at" timestamptz
  "migration_name" varchar(255) [not null]
  "logs" text
  "rolled_back_at" timestamptz
  "started_at" timestamptz [not null, default: `now()`]
  "applied_steps_count" int4 [not null, default: 0]
}

Table "User" {
  "id" text [pk, not null]
  "fullname" text [not null]
  "email" text [unique, not null]
  "password" text [not null]
  "phone" text [unique, not null]
  "address" text
  "image" text
  "positionId" text
  "teamId" text
  "genId" text
  "role" "Role[]" [default: `ARRAY['MEMBER']`]
  "status" UserStatus [not null, default: 'INACTIVE']
  "codeId" text
  "codeExpiredAt" timestamp
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "UserActions" {
  "id" text [pk, not null]
  "userId" text [not null]
  "action" text [not null]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "Team" {
  "id" text [pk, not null]
  "name" text [not null]
  "description" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Position" {
  "id" text [pk, not null]
  "name" text [not null]
  "description" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Gen" {
  "id" text [pk, not null]
  "name" text [not null]
  "description" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Task" {
  "id" text [pk, not null]
  "title" text [not null]
  "note" jsonb
  "position" float8 [not null]
  "color" text
  "type" TaskType [not null, default: 'TODO']
  "status" TaskStatus [not null, default: 'TODO']
  "priority" TaskPriority [not null, default: 'MEDIUM']
  "startDate" timestamp [not null]
  "deadline" timestamp [not null]
  "workspaceId" text [not null]
  "monthlySegmentId" text
  "isDeleted" bool [not null, default: false]
  "deletedAt" timestamp
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "TodoList" {
  "id" text [pk, not null]
  "order" int2 [not null, default: 0]
  "content" text [not null]
  "startDate" timestamp [not null]
  "deadline" timestamp [not null]
  "taskId" text [not null]

  Indexes {
    taskId [type: btree, name: "TodoList_taskId_idx"]
  }
}

Table "TaskComment" {
  "id" text [pk, not null]
  "content" text [not null]
  "taskId" text [not null]
  "userId" text [not null]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "TaskAttachment" {
  "id" text [pk, not null]
  "title" text [not null]
  "url" text [not null]
  "taskId" text [not null]
  "userId" text [not null]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "TaskActivity" {
  "id" text [pk, not null]
  "content" text [not null]
  "taskId" text [not null]
  "userId" text [not null]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Workspace" {
  "id" text [pk, not null]
  "name" text [not null]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "MonthlySegment" {
  "id" text [pk, not null]
  "name" text [not null]
  "description" text
  "frequency" int4 [not null, default: 1]
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "TeamSegment" {
  "teamId" text [not null]
  "monthlySegmentId" text [not null]
  "number_of_assignee" int4

  Indexes {
    (teamId, monthlySegmentId) [type: btree, name: "TeamSegment_pkey"]
  }
}

Table "LatestPublication" {
  "id" text [pk, not null]
  "title" text [not null]
  "description" text
  "embed_code" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "NewestProducts" {
  "id" text [pk, not null]
  "title" text [not null]
  "date" timestamp [not null]
  "description" text
  "image" text
  "link" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Memories" {
  "id" text [pk, not null]
  "title" text [not null]
  "mini_title" text
  "image" text
  "link" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "Announcement" {
  "id" text [pk, not null]
  "title" text [not null]
  "description" text
  "image" text
  "link" text
  "createdAt" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updatedAt" timestamp [not null]
}

Table "_UserToWorkspace" {
  "A" text [not null]
  "B" text [not null]

  Indexes {
    (A, B) [type: btree, name: "_UserToWorkspace_AB_pkey"]
    B [type: btree, name: "_UserToWorkspace_B_index"]
  }
}

Table "_TaskToUser" {
  "A" text [not null]
  "B" text [not null]

  Indexes {
    (A, B) [type: btree, name: "_TaskToUser_AB_pkey"]
    B [type: btree, name: "_TaskToUser_B_index"]
  }
}

Table "_TodoListToUser" {
  "A" text [not null]
  "B" text [not null]

  Indexes {
    (A, B) [type: btree, name: "_TodoListToUser_AB_pkey"]
    B [type: btree, name: "_TodoListToUser_B_index"]
  }
}

Ref "Task_monthlySegmentId_fkey":"MonthlySegment"."id" < "Task"."monthlySegmentId" [update: cascade, delete: set null]

Ref "Task_workspaceId_fkey":"Workspace"."id" < "Task"."workspaceId" [update: cascade, delete: cascade]

Ref "TaskActivity_taskId_fkey":"Task"."id" < "TaskActivity"."taskId" [update: cascade, delete: cascade]

Ref "TaskActivity_userId_fkey":"User"."id" < "TaskActivity"."userId" [update: cascade, delete: cascade]

Ref "TaskAttachment_taskId_fkey":"Task"."id" < "TaskAttachment"."taskId" [update: cascade, delete: cascade]

Ref "TaskAttachment_userId_fkey":"User"."id" < "TaskAttachment"."userId" [update: cascade, delete: cascade]

Ref "TaskComment_taskId_fkey":"Task"."id" < "TaskComment"."taskId" [update: cascade, delete: cascade]

Ref "TaskComment_userId_fkey":"User"."id" < "TaskComment"."userId" [update: cascade, delete: cascade]

Ref "TeamSegment_monthlySegmentId_fkey":"MonthlySegment"."id" < "TeamSegment"."monthlySegmentId" [update: cascade, delete: restrict]

Ref "TeamSegment_teamId_fkey":"Team"."id" < "TeamSegment"."teamId" [update: cascade, delete: restrict]

Ref "TodoList_taskId_fkey":"Task"."id" < "TodoList"."taskId" [update: cascade, delete: cascade]

Ref "User_genId_fkey":"Gen"."id" < "User"."genId" [update: cascade, delete: set null]

Ref "User_positionId_fkey":"Position"."id" < "User"."positionId" [update: cascade, delete: set null]

Ref "User_teamId_fkey":"Team"."id" < "User"."teamId" [update: cascade, delete: set null]

Ref "UserActions_userId_fkey":"User"."id" < "UserActions"."userId" [update: cascade, delete: cascade]

Ref "_TaskToUser_A_fkey":"Task"."id" < "_TaskToUser"."A" [update: cascade, delete: cascade]

Ref "_TaskToUser_B_fkey":"User"."id" < "_TaskToUser"."B" [update: cascade, delete: cascade]

Ref "_TodoListToUser_A_fkey":"TodoList"."id" < "_TodoListToUser"."A" [update: cascade, delete: cascade]

Ref "_TodoListToUser_B_fkey":"User"."id" < "_TodoListToUser"."B" [update: cascade, delete: cascade]

Ref "_UserToWorkspace_A_fkey":"User"."id" < "_UserToWorkspace"."A" [update: cascade, delete: cascade]

Ref "_UserToWorkspace_B_fkey":"Workspace"."id" < "_UserToWorkspace"."B" [update: cascade, delete: cascade]
